const eventsHeading = "Upcoming events:";
const eventsTitle = "In honor of Joan Feynman: Women in astrophysics";
const eventsInfo = "Triple Peaks Library Conference Hall & Online";
const eventsDateInfo = "Mon, January 12";
const eventsDescription =
  "At this event, which celebrates the library's namesake, our guest lecturer will take us on a journey exploring some of the most prominent female researchers in the world of space science. It's easy to buy into the misconception that this field was mostly dominated by men, but our lecture aims to change that notion and prove that this hasn't been the case since at least the 18th century.";
const eventsMore = "More events";
const eventsContainer = document.querySelector(".events");
const eventsH = eventsContainer.querySelector(".events__heading");
eventsH.append(eventsHeading);
const eventsT = eventsContainer.querySelector(".events__title");
eventsT.append(eventsTitle);
const eventsDate = eventsContainer.querySelector(".event__calendar-text");
eventsDate.append(eventsDateInfo);
const eventsPin = eventsContainer.querySelector(".event__pin-text");
eventsPin.append(eventsInfo);
const eventsD = eventsContainer.querySelector(".events__description");
eventsD.append(eventsDescription);
const eventsM = eventsContainer.querySelector(".events__more");
eventsM.prepend(eventsMore);
const joan = "Joan Feyman";
const margaret = "Margaret Burbidge";
const jill = "Jill Tarter";
const annie = "Annie Jump Cannon";
const maria = "Maria Mitchell";
const joanF = document.querySelector(".person__joan");
joanF.append(joan);
const margaretB = document.querySelector(".person__margaret");
margaretB.append(margaret);
const jillT = document.querySelector(".person__jill");
jillT.append(jill);
const annieJC = document.querySelector(".person__annie");
annieJC.append(annie);
const mariaM = document.querySelector(".person__maria");
mariaM.append(maria);
